export enum ContractStatus {
  CREATED = 'CREATED',

  CREATED_PLACEMENT = 'CREATED_PLACEMENT',

  CREATED_SHARE = 'CREATED_SHARE',

  CREATED_SHARE_FINALISED = 'CREATED_SHARE_FINALISED',

  CREATED_APPROVED = 'CREATED_APPROVED',

  UPDATE_CREATED = 'UPDATE_CREATED',

  UPDATE_APPROVED = 'UPDATE_APPROVED',
}
