package za.co.afrikatek.brokingservice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InsuranceTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceTypeAllPropertiesEquals(InsuranceType expected, InsuranceType actual) {
        assertInsuranceTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertInsuranceTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceTypeAllUpdatablePropertiesEquals(InsuranceType expected, InsuranceType actual) {
        assertInsuranceTypeUpdatableFieldsEquals(expected, actual);
        assertInsuranceTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceTypeAutoGeneratedPropertiesEquals(InsuranceType expected, InsuranceType actual) {
        assertThat(expected)
            .as("Verify InsuranceType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceTypeUpdatableFieldsEquals(InsuranceType expected, InsuranceType actual) {
        assertThat(expected)
            .as("Verify InsuranceType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsuranceTypeUpdatableRelationshipsEquals(InsuranceType expected, InsuranceType actual) {}
}
